// Copyright 2013 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:polymer/builder.dart';
import 'dart:io';

const OPT_CHANGED = "--changed=";

void main() {
  /*
  final args = new Options().arguments;
  final changed = args.where((opt) => opt.startsWith(OPT_CHANGED))
                      .map((opt) => opt.substring(OPT_CHANGED.length));

  // If list of changed files is empty (forced rebuild) or there are
  // changed files that are not autogenerated then copy demo files.
  if (changed.isEmpty ||
      !changed.where((file) => !file.startsWith("web/out")).isEmpty) {
    Process.run("./bin/build.sh", []);
  }*/

  build(entryPoints: ['web/index.html']);
}